name: collecto_data
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  dio: ^5.8.0+1

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
